
All playbooks are written in YAML. 
A playbook is combination of play.
A play is combination of activity ot Tasks.
Task Uses YAML modules to perform the activity.


Tasks example: Execte command, Install software, reboot a server etc etc..

====================== Exercise =====================
cd ~
mkdir ansible-demo
cd ansible-demo
mkdir default-web/
echo " This is Test website" > index.html

================
vi myplaybookping.yaml


-
  name: Test connectivity to the target servers
  hosts: all
  tasks:
    - name: ping test
      ping:

ansible-playbook myplaybookping.yaml -i <inventory_file_path>

=====================================================
vi network.yaml

---
- 
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "Show Network Interfaces"
      command: ifconfig
      register: details
    - name: 'Get Interfaces details'
      debug:
        msg: "{{ details.stdout }}"

ansible-playbook network.yaml

==============================

======
vi patching.yam
---
- hosts: webservers
  tasks:
    - name: "Update all packages to the latest version"
      apt:
        upgrade: dist



===========


================
Install Nginx on Ubuntu
========================
---
- hosts: WebServer
  tasks:
    - name: "Install NginX"
      apt:
        name: nginx
        state: present

    - name: "Start Nginx Services"
      service:
        name: nginx
        state: started

    - name: "Deploy Website"
      become: true
      synchronize:
        dest: /var/www/html
        src: ../default-web/

    - name: "Set Directory Owner"
      become: true
      file:
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: 0755
        recurse: yes
========================
Un-Install Nginx on Ubuntu

---
- hosts: webservers
  tasks:
    - name: "Uninstall NginX"
      apt:
        name: nginx
        state: absent

    - name: "Stop Nginx Services"
      service:
        name: nginx
        state: stopped

========================


Git Clone:
git clone https://github.com/davestephens/ansible-ubuntu-wordpress.git